name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: jarpsimoes
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jarpsimoes/git_http_server:v0.${SHORT_SHA}
    
    - name: Push Image
      run: docker push jarpsimoes/git_http_server:v0.${SHORT_SHA}
