name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN_TESTS }}
  ACCESS_USERNAME: html_sample
  CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_TOKEN }}
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Calc coverage
        run: |
          cd src
          go test -v ./... -covermode=count -coverprofile=coverage.out
      - name: Convert coverage.out to coverage.lcov
        uses: jandelgado/gcov2lcov-action@v1.0.6
        with:
          working-directory: src
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.CODECOV_TOKEN }}
          path-to-lcov: src/coverage.lcov
          base-path: src
          
  build:

    runs-on: ubuntu-latest
    needs: coverage
    steps:
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: jarpsimoes
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag jarpsimoes/git_http_server:v0.${SHORT_SHA}

      - name: Push Image
        run: docker push jarpsimoes/git_http_server:v0.${SHORT_SHA}

      - name: Push Latest
        run: docker tag jarpsimoes/git_http_server:v0.${SHORT_SHA} jarpsimoes/git_http_server:latest && docker push jarpsimoes/git_http_server:latest
